name: sample1
on: [push]
jobs:
  explore-first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "czesc"
      - name: Check
        uses: actions/checkout@v2
      - run: |
          ls ${{ github.workspace }}
